name: xarray-tutorial
channels:
  - conda-forge
  - default
dependencies:
  - python=3.6
  - numpy
  - scipy
  - pandas
  - xarray
  - holoviews
  - geoviews
  - datashader
  - dask
  - distributed
  - netcdf4
  - zarr
  - nbserverproxy
  - pip:
    - dask-kubernetes
